//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unique.EcommGroceryStore.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public int CartDetailId { get; set; }
        public Nullable<int> CartId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public System.DateTime Timestamp { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> PricePerUnit { get; set; }
        public string Unit { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual ProductDetails ProductDetails { get; set; }
    }
}
