//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unique.EcommGroceryStore.DAL.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EcommGroceryDataContext : DbContext
    {
        public EcommGroceryDataContext()
            : base("name=EcommGroceryDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressDetails> AddressDetails { get; set; }
        public virtual DbSet<AreaMaster> AreaMaster { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<CartDetail> CartDetail { get; set; }
        public virtual DbSet<CityMaster> CityMaster { get; set; }
        public virtual DbSet<CountryMaster> CountryMaster { get; set; }
        public virtual DbSet<CouponDetails> CouponDetails { get; set; }
        public virtual DbSet<FollowUpDetails> FollowUpDetails { get; set; }
        public virtual DbSet<MainCategoryMaster> MainCategoryMaster { get; set; }
        public virtual DbSet<ProductDetails> ProductDetails { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SubCategoryMaster> SubCategoryMaster { get; set; }
        public virtual DbSet<TransactionDetails> TransactionDetails { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<Sp_GetProductDetailsList_Result> Sp_GetProductDetailsList(Nullable<int> currentIndex, Nullable<int> pageSize, string orderByClause, string search, Nullable<int> mainCategoryId, Nullable<int> subCategoryId, ObjectParameter totalRecords)
        {
            var currentIndexParameter = currentIndex.HasValue ?
                new ObjectParameter("currentIndex", currentIndex) :
                new ObjectParameter("currentIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var orderByClauseParameter = orderByClause != null ?
                new ObjectParameter("orderByClause", orderByClause) :
                new ObjectParameter("orderByClause", typeof(string));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            var mainCategoryIdParameter = mainCategoryId.HasValue ?
                new ObjectParameter("MainCategoryId", mainCategoryId) :
                new ObjectParameter("MainCategoryId", typeof(int));
    
            var subCategoryIdParameter = subCategoryId.HasValue ?
                new ObjectParameter("SubCategoryId", subCategoryId) :
                new ObjectParameter("SubCategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetProductDetailsList_Result>("Sp_GetProductDetailsList", currentIndexParameter, pageSizeParameter, orderByClauseParameter, searchParameter, mainCategoryIdParameter, subCategoryIdParameter, totalRecords);
        }
    
        public virtual ObjectResult<Sp_GetTransactionList_Result> Sp_GetTransactionList(Nullable<int> cartId, Nullable<int> op)
        {
            var cartIdParameter = cartId.HasValue ?
                new ObjectParameter("CartId", cartId) :
                new ObjectParameter("CartId", typeof(int));
    
            var opParameter = op.HasValue ?
                new ObjectParameter("Op", op) :
                new ObjectParameter("Op", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetTransactionList_Result>("Sp_GetTransactionList", cartIdParameter, opParameter);
        }
    
        public virtual ObjectResult<Sp_GetUserList_Result> Sp_GetUserList(Nullable<int> currentIndex, Nullable<int> pageSize, string orderByClause, string search, ObjectParameter totalRecords)
        {
            var currentIndexParameter = currentIndex.HasValue ?
                new ObjectParameter("currentIndex", currentIndex) :
                new ObjectParameter("currentIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var orderByClauseParameter = orderByClause != null ?
                new ObjectParameter("orderByClause", orderByClause) :
                new ObjectParameter("orderByClause", typeof(string));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetUserList_Result>("Sp_GetUserList", currentIndexParameter, pageSizeParameter, orderByClauseParameter, searchParameter, totalRecords);
        }
    
        public virtual ObjectResult<Sp_GetUserTransactionList_Result> Sp_GetUserTransactionList(Nullable<int> currentIndex, Nullable<int> pageSize, string orderByClause, string search, ObjectParameter totalRecords)
        {
            var currentIndexParameter = currentIndex.HasValue ?
                new ObjectParameter("currentIndex", currentIndex) :
                new ObjectParameter("currentIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var orderByClauseParameter = orderByClause != null ?
                new ObjectParameter("orderByClause", orderByClause) :
                new ObjectParameter("orderByClause", typeof(string));
    
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetUserTransactionList_Result>("Sp_GetUserTransactionList", currentIndexParameter, pageSizeParameter, orderByClauseParameter, searchParameter, totalRecords);
        }
    
        public virtual int Sp_UpdateDeleteProduct(Nullable<int> productId, Nullable<bool> productStatus, ObjectParameter status, Nullable<int> op)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            var productStatusParameter = productStatus.HasValue ?
                new ObjectParameter("ProductStatus", productStatus) :
                new ObjectParameter("ProductStatus", typeof(bool));
    
            var opParameter = op.HasValue ?
                new ObjectParameter("Op", op) :
                new ObjectParameter("Op", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UpdateDeleteProduct", productIdParameter, productStatusParameter, status, opParameter);
        }
    
        public virtual int Sp_UpdateDeleteUser(Nullable<int> userId, Nullable<bool> userStatus, ObjectParameter status, Nullable<int> op)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var userStatusParameter = userStatus.HasValue ?
                new ObjectParameter("UserStatus", userStatus) :
                new ObjectParameter("UserStatus", typeof(bool));
    
            var opParameter = op.HasValue ?
                new ObjectParameter("Op", op) :
                new ObjectParameter("Op", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UpdateDeleteUser", userIdParameter, userStatusParameter, status, opParameter);
        }
    }
}
