//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unique.EcommGroceryStore.DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDetails()
        {
            this.CartDetail = new HashSet<CartDetail>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int SubCategoryId { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public int PricePerUnit { get; set; }
        public string Unit { get; set; }
        public bool Status { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsOutOfStock { get; set; }
        public bool IsLimitedStock { get; set; }
        public bool IsSeasonalStock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartDetail> CartDetail { get; set; }
        public virtual SubCategoryMaster SubCategoryMaster { get; set; }
    }
}
